theme: jekyll-theme-minimal

title: Jaydeep Singh
logo: IMG-20190817-WA0004.jpg
description: Senior Research Fellow @ Atmospheric Devision, ARIES Nainital
email: jaydeep@aries.res.in
twitter_username: jaydeeptindori
github_username: jaydeeptindori
