theme: jekyll-theme-minimal

title: Jaydeep Singh
logo: 1608441684665.jpg
description: Senior Research Fellow @ Atmospheric Devision, ARIES Nainital
email: jaydeep@aries.res.in
twitter_username: jaydeeptindori
github_username: jaydeeptindori
show_downloads: false


plugins:
 - jekyll-feed
 - jekyll-seo-tag
